name: container image linting

on:
  workflow_call:

jobs:
  image-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
# TODO
