on:
    workflow_call:

jobs:
    hawkeye:
        name: hawkeye
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}
# TODO
