name: java linting, gradle linting, and jacoco coverage

on:
  workflow_call:

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
# TODO
