name: searching for 3rd party vulnerabilities in node dependencies using npm audit

on:
  workflow_call:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
# TODO
